services:

  postgres:

    image: postgres:17

    container_name: postgres

    restart: always

    environment:

      POSTGRES_DB: linkr

      POSTGRES_USER: postgres

      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d linkr"]
      interval: 5s
      timeout: 5s
      retries: 5

    ports:

      - "5432:5432"

    volumes:

      - postgres_data:/var/lib/postgresql/data

      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    

  backend:

    build: ./backend

    container_name: backend

    ports:

      - "8080:8080"

    env_file:

      - ./backend/.env

    depends_on:
      postgres:
        condition: service_healthy

  frontend:

    build: 
      context: ./frontend
      args:
        NEXT_PUBLIC_API: http://localhost:8080

        NEXT_PUBLIC_REGION: ap-south-1

        NEXT_PUBLIC_POOL_ID: ap-south-1_VofpQSNp2

        NEXT_PUBLIC_CLIENT_ID: 6p91k8ssnakkc4taq9mtd4th9k

    container_name: frontend

    ports:

      - "3000:3000"

    env_file:

      - ./frontend/.env.local

    depends_on:

      - backend

volumes:

  postgres_data: