services:

  postgres:

    image: postgres:16

    container_name: linkr-postgres

    environment:

      POSTGRES_USER: postgres

      POSTGRES_PASSWORD: postgres

      POSTGRES_DB: linkr


    ports:

      - "5432:5432"


    volumes:

      - postgres-data:/var/lib/postgresql/data

      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql



    healthcheck:

      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres"
        ]

      interval: 5s

      timeout: 5s

      retries: 10



  backend:

    build:

      context: ./backend


    container_name: linkr-backend


    environment:


      PORT: 8080


      DATABASE_URL:
        postgres://postgres:postgres@postgres:5432/linkr?sslmode=disable


      BASE_URL:
        http://localhost:8080


      COGNITO_POOL_ID:
        ${COGNITO_POOL_ID}


      COGNITO_CLIENT_ID:
        ${COGNITO_CLIENT_ID}


      COGNITO_REGION:
        ${COGNITO_REGION}



    ports:

      - "8080:8080"



    depends_on:

      postgres:

        condition: service_healthy



  frontend:


    build:

      context: ./frontend



    container_name: linkr-frontend



    environment:


      NEXT_PUBLIC_API:

        http://localhost:8080



      NEXT_PUBLIC_POOL_ID:

        ${COGNITO_POOL_ID}



      NEXT_PUBLIC_CLIENT_ID:

        ${COGNITO_CLIENT_ID}



    ports:

      - "3000:3000"



    depends_on:

      - backend



volumes:

  postgres-data: